backend:
  name: git-gateway
  repo: orohellec/my_website
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: projet
    label: Projet
    folder: src/markdown-pages/projects
    create: true
    fields:
      - { name: type, label: Type }
      - { name: title, label: Titre }
      - { name: path, label: Chemin (/portfolio/...) }
      - { name: imgName, label: Nom de l'image }
      - { name: concept, label: Concept }
      - { name: description, label: Description }
      - { name: stack, label: Stack (format ruby,rails,javascript...)}
      - { name: gitHubLink, label: Lien Github }
      - { name: prodLink, label: Lien de l'application en production }
      
