backend:
  name: git-gateway
  repo: orohellec/my_website
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: projet
    label: Projet
    folder: src/markdown-pages/projects
    create: true
    fields:
      - { name: type, label: Type, widget: string }
      - { name: title, label: Titre, widget: string }
      - { name: path, label: Chemin (/portfolio/...), widget: string }
      - { name: imgName, label: Nom de l'image, widget: string }
      - { name: concept, label: Concept, widget: text }
      - { name: description, label: Description, widget: text }
      - { name: stack, label: Stack (format ruby,rails,javascript...), widget: string }
      - { name: githubLink, label: Lien Github, widget: string }
      - { name: prodLink, label: Lien de l'application en production, widget: string }
      
